# Gabriel AI Platform - Port Conflict Resolution
# Manual configuration to avoid system service conflicts

version: '3.8'

services:
  # Database Services - Using high ports to avoid conflicts
  gabriel-db:
    image: postgres:15
    container_name: gabriel-db
    environment:
      POSTGRES_DB: gabriel_ai
      POSTGRES_USER: gabriel_user
      POSTGRES_PASSWORD: gabriel_secure_2025
    volumes:
      - gabriel_db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"    # Changed from 5432 to 15432 (high port, unlikely conflict)
    networks:
      - gabriel-network

  gabriel-redis:
    image: redis:7-alpine
    container_name: gabriel-redis
    ports:
      - "16379:6379"    # Changed from 6379 to 16379 (high port, unlikely conflict)
    networks:
      - gabriel-network

  # Gabriel AI Microservices - Using 9000+ range
  gabriel-core:
    build: ./containers/gabriel-core
    container_name: gabriel-core
    ports:
      - "9000:8000"     # Core API Gateway
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - REDIS_HOST=gabriel-redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - CULTURAL_INTELLIGENCE_ENGINE=configurable
      - DEFAULT_CULTURAL_CONTEXT=nigeria_launch
      - GLOBAL_EXPANSION_READY=true
    depends_on:
      - gabriel-db
      - gabriel-redis
    networks:
      - gabriel-network
    volumes:
      - ./shared:/app/shared

  gabriel-users:
    build: ./containers/gabriel-users
    container_name: gabriel-users
    ports:
      - "9001:8001"     # User Management
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - CULTURAL_PROFILE_FEATURES=multi_region_support
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-courses:
    build: ./containers/gabriel-courses
    container_name: gabriel-courses
    ports:
      - "9002:8002"     # Course Management
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - DUAL_MODE_CURRICULUM=remote_local_career
      - GLOBAL_CURRICULUM_STANDARDS=enabled
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-virtual-human:
    build: ./containers/gabriel-virtual-human
    container_name: gabriel-virtual-human
    ports:
      - "9003:8003"     # Virtual Human & TTS
    environment:
      - NODE_ENV=development
      - TTS_ENGINE=multi_accent_synthesis
      - CULTURAL_VOICE_PROFILES=configurable_by_region
    networks:
      - gabriel-network

  gabriel-assessments:
    build: ./containers/gabriel-assessments
    container_name: gabriel-assessments
    ports:
      - "9004:8004"     # Assessment Engine
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - EMPLOYER_READINESS_STANDARDS=global_remote_local_configurable
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-ocr:
    build: ./containers/gabriel-ocr
    container_name: gabriel-ocr
    ports:
      - "9005:8005"     # OCR Processing
    environment:
      - NODE_ENV=development
      - OCR_ENGINE=tesseract_optimized_mobile
      - MOBILE_CAMERA_OPTIMIZATION=enabled
    networks:
      - gabriel-network

  gabriel-ai-tutoring:
    build: ./containers/gabriel-ai-tutoring
    container_name: gabriel-ai-tutoring
    ports:
      - "9006:8006"     # AI Tutoring
    environment:
      - NODE_ENV=development
      - CLOUDFLARE_BACKEND_INTEGRATION=https://gabriel-ai-backend.peoplemerit.workers.dev
      - CULTURAL_CONTEXT_ENGINE=configurable_regional_standards
    networks:
      - gabriel-network

  gabriel-career:
    build: ./containers/gabriel-career
    container_name: gabriel-career
    ports:
      - "9007:8007"     # Career Assessment
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - CAREER_MODES=global_remote_local_configurable
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-payments:
    build: ./containers/gabriel-payments
    container_name: gabriel-payments
    ports:
      - "9008:8008"     # Payment Processing
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - PAYMENT_PROVIDERS=multi_regional_mobile_money_global_cards
      - FREE_FIRST_MODEL=enabled
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-communication:
    build: ./containers/gabriel-communication
    container_name: gabriel-communication
    ports:
      - "9009:8009"     # Multi-language Communication
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - MULTI_LANGUAGE_SUPPORT=configurable_by_region
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

  gabriel-analytics:
    build: ./containers/gabriel-analytics
    container_name: gabriel-analytics
    ports:
      - "9010:8010"     # Analytics & Impact Tracking
    environment:
      - NODE_ENV=development
      - DB_HOST=gabriel-db
      - DB_PORT=5432
      - EMPLOYMENT_OUTCOME_TRACKING=enabled
      - GLOBAL_ANALYTICS_FRAMEWORK=enabled
    depends_on:
      - gabriel-db
    networks:
      - gabriel-network

volumes:
  gabriel_db_data:

networks:
  gabriel-network:
    driver: bridge

# Port Summary:
# Database: PostgreSQL 15432, Redis 16379
# Services: 9000-9010 (Core, Users, Courses, Virtual Human, Assessments, OCR, AI Tutoring, Career, Payments, Communication, Analytics)
# 
# These ports should be completely free of conflicts!
