name: Feature Request
description: Suggest a new feature or enhancement for the PMERIT platform
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've considered...
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the platform does this feature relate to?
      options:
        - Assessment Experience
        - Results & Recommendations
        - Virtual Human / AI Assistant
        - User Interface / Design
        - Performance / Speed
        - Mobile Experience
        - Accessibility
        - PDF Export / Sharing
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-impact
    attributes:
      label: User Impact
      description: How many users would benefit from this feature?
      options:
        - All users
        - Most users
        - Some users
        - Power users / specific use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: Describe a specific scenario where this feature would be useful.
      placeholder: "As a [type of user], I want to [do something] so that [benefit/goal]..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other platforms. You can drag and drop images here.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority / Urgency
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for user satisfaction
        - Critical - Blocking or essential
      default: 1
    validations:
      required: true
