name: Question
description: Ask a question about using the PMERIT platform
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide details below.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - How to use a feature
        - Assessment questions
        - Results interpretation
        - Career recommendations
        - Virtual Human / AI Assistant
        - Technical issue / Error
        - Account / Access
        - General inquiry
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Is there any additional context that would help us answer your question?
      placeholder: |
        - What were you trying to do?
        - What page were you on?
        - Any error messages you saw?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help illustrate your question. You can drag and drop images here.
      placeholder: Drag and drop screenshots here...
    validations:
      required: false

  - type: checkboxes
    id: documentation-check
    attributes:
      label: Documentation Check
      description: Have you checked our existing documentation?
      options:
        - label: I have checked the [User Guide](https://github.com/peoplemerit/pmerit-ai-platform/blob/main/docs/USER_GUIDE.md)
        - label: I have checked the [FAQ section](https://github.com/peoplemerit/pmerit-ai-platform/blob/main/docs/USER_GUIDE.md#faq)
        - label: I have searched for similar questions in existing issues
