version: '3.8'

networks:
  pmerit-network:
    driver: bridge

volumes:
  pmerit_core_data:
    driver: local
  pmerit_ai_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

services:
  # =================================================================
  # CORE AUTHENTICATION DATABASE (High Port 15432)
  # =================================================================
  pmerit-core-db:
    image: postgres:15-alpine
    container_name: pmerit-core-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pmerit_core
      POSTGRES_USER: pmerit_admin
      POSTGRES_PASSWORD: pmerit_secure_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "15432:5432"  # ← Using high number port 15432
    volumes:
      - pmerit_core_data:/var/lib/postgresql/data
      - ./scripts/init/core_init.sql:/docker-entrypoint-initdb.d/01-core-init.sql
    networks:
      - pmerit-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmerit_admin -d pmerit_core"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =================================================================
  # AI INTELLIGENCE DATABASE (Keep working port 5434)
  # =================================================================
  pmerit-ai-db:
    image: postgres:15-alpine
    container_name: pmerit-ai-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pmerit_ai
      POSTGRES_USER: pmerit_admin
      POSTGRES_PASSWORD: pmerit_secure_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"  # ← Keep this - it works!
    volumes:
      - pmerit_ai_data:/var/lib/postgresql/data
      - ./scripts/init/ai_init.sql:/docker-entrypoint-initdb.d/01-ai-init.sql
    networks:
      - pmerit-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.8'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmerit_admin -d pmerit_ai"]
      interval: 15s
      timeout: 5s
      retries: 3

  # =================================================================
  # REDIS CACHE (High Port 16379)
  # =================================================================
  pmerit-redis:
    image: redis:7-alpine
    container_name: pmerit-redis
    restart: unless-stopped
    ports:
      - "16379:6379"  # ← Using high number port 16379
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - pmerit-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server /usr/local/etc/redis/redis.conf

  # =================================================================
  # PGADMIN - DATABASE MANAGEMENT GUI (Port 18080)
  # =================================================================
  pmerit-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pmerit-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pmerit.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "18081:80"  # ← Changed to 18080 to be safe
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    networks:
      - pmerit-network
    depends_on:
      - pmerit-core-db
      - pmerit-ai-db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
