-- ============================================================================
-- PMERIT Assessment Tables Migration
-- Migration: 001_assessment_tables.sql
-- Created: November 3, 2025
-- Issue: #18 - Database Integration & Schema Verification
-- ============================================================================
--
-- This migration creates the core tables for the PMERIT Assessment System:
-- 1. assessment_sessions - Tracks user assessment progress
-- 2. assessment_results - Stores completed assessment results
--
-- Prerequisites:
-- - Neon PostgreSQL database with Hyperdrive connection
-- - 'users' table must exist with 'id' column
--
-- Usage:
-- Run this script against your Neon database to create the schema
-- ============================================================================

-- ============================================================================
-- TABLE: assessment_sessions
-- Purpose: Track individual assessment sessions with progress and consent
-- ============================================================================

CREATE TABLE IF NOT EXISTS assessment_sessions (
    -- Primary Key
    id SERIAL PRIMARY KEY,
    
    -- Session Identifier (UUID generated by database)
    session_id UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    
    -- User Reference (nullable for anonymous users)
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    
    -- Consent Data (JSONB storing privacy, data, terms consent)
    consent_data JSONB NOT NULL,
    
    -- Progress Tracking
    current_question INTEGER DEFAULT 0 NOT NULL CHECK (current_question >= 0 AND current_question <= 119),
    
    -- Assessment Answers (JSONB object: {question_id: answer_value})
    answers JSONB DEFAULT '{}'::jsonb,
    
    -- Session Status
    status VARCHAR(20) DEFAULT 'started' NOT NULL 
        CHECK (status IN ('started', 'in_progress', 'completed', 'abandoned')),
    
    -- Timestamps
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ============================================================================
-- INDEXES for assessment_sessions
-- ============================================================================

-- Index 1: Fast lookup by session_id (most common query)
CREATE INDEX IF NOT EXISTS idx_assessment_sessions_session_id 
    ON assessment_sessions(session_id);

-- Index 2: User's sessions lookup
CREATE INDEX IF NOT EXISTS idx_assessment_sessions_user_id 
    ON assessment_sessions(user_id) 
    WHERE user_id IS NOT NULL;

-- Index 3: Filter by status and date for analytics
CREATE INDEX IF NOT EXISTS idx_assessment_sessions_status_created 
    ON assessment_sessions(status, created_at DESC);

-- Index 4: Updated timestamp for finding stale sessions
CREATE INDEX IF NOT EXISTS idx_assessment_sessions_updated_at 
    ON assessment_sessions(updated_at DESC);

-- ============================================================================
-- TABLE: assessment_results
-- Purpose: Store completed assessment results with personality scores
-- ============================================================================

CREATE TABLE IF NOT EXISTS assessment_results (
    -- Primary Key
    id SERIAL PRIMARY KEY,
    
    -- Result Identifier (UUID generated by database)
    result_id UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    
    -- Foreign Keys
    session_id UUID NOT NULL REFERENCES assessment_sessions(session_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    
    -- Big Five Personality Traits (JSONB with structure: 
    -- {trait: {raw: number, percentile: number, label: string}})
    big_five JSONB NOT NULL,
    
    -- Holland RIASEC Code (3 letters from RIASEC, e.g., "IAE")
    holland_code VARCHAR(3) NOT NULL CHECK (holland_code ~ '^[RIASEC]{3}$'),
    
    -- Career Matches (JSONB array of career objects with scores)
    career_matches JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    -- Timestamps
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ============================================================================
-- INDEXES for assessment_results
-- ============================================================================

-- Index 1: Fast lookup by result_id
CREATE INDEX IF NOT EXISTS idx_assessment_results_result_id 
    ON assessment_results(result_id);

-- Index 2: Lookup results by session
CREATE INDEX IF NOT EXISTS idx_assessment_results_session_id 
    ON assessment_results(session_id);

-- Index 3: User's assessment history
CREATE INDEX IF NOT EXISTS idx_assessment_results_user_id 
    ON assessment_results(user_id, completed_at DESC) 
    WHERE user_id IS NOT NULL;

-- Index 4: Holland Code analysis for career matching
CREATE INDEX IF NOT EXISTS idx_assessment_results_holland_code 
    ON assessment_results(holland_code, completed_at DESC);

-- ============================================================================
-- COMMENTS (Optional: PostgreSQL supports table/column comments)
-- ============================================================================

COMMENT ON TABLE assessment_sessions IS 'Tracks user assessment progress with consent and answers';
COMMENT ON COLUMN assessment_sessions.session_id IS 'Unique UUID identifier for session';
COMMENT ON COLUMN assessment_sessions.consent_data IS 'User consent for privacy, data usage, and terms';
COMMENT ON COLUMN assessment_sessions.answers IS 'JSONB object storing question_id to answer_value mappings';
COMMENT ON COLUMN assessment_sessions.current_question IS 'Current question index (0-119) for progress tracking';

COMMENT ON TABLE assessment_results IS 'Stores completed assessment results with personality analysis';
COMMENT ON COLUMN assessment_results.result_id IS 'Unique UUID identifier for results';
COMMENT ON COLUMN assessment_results.big_five IS 'Big Five personality traits with raw scores, percentiles, and labels';
COMMENT ON COLUMN assessment_results.holland_code IS 'Three-letter RIASEC code (e.g., IAE, RSE, ASE)';
COMMENT ON COLUMN assessment_results.career_matches IS 'Array of career matches with fit scores';

-- ============================================================================
-- VERIFICATION QUERIES (Optional: Use to verify schema)
-- ============================================================================

-- Check tables exist
-- SELECT table_name FROM information_schema.tables 
-- WHERE table_schema = 'public' AND table_name IN ('assessment_sessions', 'assessment_results');

-- Check columns
-- SELECT column_name, data_type, is_nullable, column_default 
-- FROM information_schema.columns 
-- WHERE table_name = 'assessment_sessions' 
-- ORDER BY ordinal_position;

-- Check constraints
-- SELECT constraint_name, constraint_type 
-- FROM information_schema.table_constraints 
-- WHERE table_name IN ('assessment_sessions', 'assessment_results');

-- Check indexes
-- SELECT indexname, indexdef 
-- FROM pg_indexes 
-- WHERE tablename IN ('assessment_sessions', 'assessment_results');

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
